version: '3.6'
services:
  postgres:
    env_file: .env
    image: mdillon/postgis
    ports:
      - '${DB_HOST_PORT}:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    ports:
      - '3000:3000'
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres

  graphql-engine:
    env_file: .env
    image: hasura/graphql-engine:v1.1.0
    ports:
      - '${HASURA_HOST_PORT}:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      #   HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDATCCAemgAwIBAgIJd9gxJgN+fJZXMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV\nBAMTE2ZseWVyLWRheS5hdXRoMC5jb20wHhcNMjAwMTI0MDAzMDIwWhcNMzMxMDAy\nMDAzMDIwWjAeMRwwGgYDVQQDExNmbHllci1kYXkuYXV0aDAuY29tMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr2WHfwrs4ArFggHRTvj16u7394NSNPuF\nP9Gxlk9XdFw4FW4C9yLF0SAeRkjv5XEVNYFPD7QOuiAiX4fRm0KjAhJNuan34YbH\nuBhGh+mWll+B5YppUovwe7AtNRQPBtjx1XxG7QbpWsxFj6uo4k9YcBZf7iszVTPq\nOoFQeTxFgQQOHUYgAw412oapc4VWylWXyUcuMLq3E1awGSqqyQEXXl3k1/wlIzXM\nU1H860vdMUrqXdHcbE1vtmKE1cQ4pr8L4pqvr2bnnzTMdFDJ4H/MlcixkJ43KqYr\nHF8L/12XSllgv/xYhsEGTYZZDt2rkI5wSH/r9h1bwRQY7BJFrhYzSwIDAQABo0Iw\nQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTXNlgvret+XQP83F7AzuQQbSr5\n8zAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAHL6HtA+zHgEWv0J\nmBRjq40cuIC/+81OgI5gswLEvKpOvEPnJf7aFQhgS3gv28LebwrfUvIa0RN1M+Sz\nUogBs3s+LP2ql1t+xSEsCc0O5Rd4bMYFhVCWgmujzONvLpx1ckiTj8Kpp1w8miI+\nCCdmptgV9hJEoohp5MpFCtMHWRR+nAdj+SYYrjeO9Xpmx178B7eUjOc2B+QUxMZf\nMvHzLdSgrJFWp+Ky0QyXx5FG3iqqWn21ZFVqEez4erdMxr0fcjQhIcPPRHK9S7JR\nmRCzAMC0SwP0Ux6nG5axAukLqLfGZSVwbUMJF0nkKH265hzYxdTCsN4pMawcVTv4\ntf3hPuM=\n-----END CERTIFICATE-----\n"}'
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R"}'
      HASURA_GRAPHQL_ADMIN_SECRET: secret

volumes:
  db_data:
